version: "3.8"

services:
  dev:
    build: .
    volumes:
      - .:/app
      - deps_cache:/app/deps_cache
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: "host"
    command: /bin/bash
    tty: true
    stdin_open: true
