name: Auto Version

on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled, closed]
    branches: ["main", "master"]

jobs:
  validate-labels:
    runs-on: ubuntu-latest
    # Only validate on non-merge events
    if: github.event.action != 'closed'
    permissions:
      pull-requests: write # Need write to update PR description
      statuses: write
      checks: write

    steps:
      - uses: actions/checkout@v4

      - name: Calculate Next Version
        id: version
        run: |
          # Read current version
          CURRENT_VERSION=$(cat version.txt)
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"

          # Determine bump type
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" == "true" ]]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
            BUMP_TYPE="major"
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'minor') }}" == "true" ]]; then
            MINOR=$((MINOR + 1))
            PATCH=0
            BUMP_TYPE="minor"
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'patch') }}" == "true" ]]; then
            PATCH=$((PATCH + 1))
            BUMP_TYPE="patch"
          fi

          # Create new version string
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "bump_type=${BUMP_TYPE}" >> $GITHUB_OUTPUT

      - name: Validate Version Labels
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(l => l.name);
            const versionLabels = ['major', 'minor', 'patch'].filter(l => labels.includes(l));

            if (versionLabels.length > 1) {
              core.setFailed('Multiple version indicators found. Please use only one major, minor, or patch label.');
              return;
            }

            // Store the next version in the PR description
            if (versionLabels.length === 1) {
              const newVersion = '${{ steps.version.outputs.new_version }}';
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                body: `Next version: ${newVersion}\n\n${context.payload.pull_request.body || ''}`
              });
            }

  generate-release:
    runs-on: ubuntu-latest
    # Only run on merge
    if: github.event.pull_request.merged == true
    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Next Version
        id: version
        run: |
          # Extract version from PR description
          BODY="${{ github.event.pull_request.body }}"
          NEW_VERSION=$(echo "$BODY" | grep -oP 'Next version: \K[0-9]+\.[0-9]+\.[0-9]+')
          echo "new_version=${NEW_VERSION}" >> $GITHUB_OUTPUT
          echo "$NEW_VERSION" > version.txt

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.pull_request.head.sha }}
          name: game-engine-v${{ steps.version.outputs.new_version }}
          path: package
        continue-on-error: true

      - name: Debug Artifact Info
        run: |
          echo "PR SHA: ${{ github.event.pull_request.head.sha }}"
          echo "New Version: ${{ steps.version.outputs.new_version }}"
          ls -la package/ || echo "Package directory not found"

      - name: Create Release Package
        run: |
          cd package
          zip -r ../GameEngine-v${{ steps.version.outputs.new_version }}.zip *

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create Git Tag and Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add version.txt
          git commit -m "Bump version to ${{ steps.version.outputs.new_version }}"
          git tag -a "v${{ steps.version.outputs.new_version }}" -m "Version ${{ steps.version.outputs.new_version }}"
          git push origin HEAD:${GITHUB_REF#refs/heads/}
          git push origin "v${{ steps.version.outputs.new_version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: GameEngine v${{ steps.version.outputs.new_version }}
          tag_name: v${{ steps.version.outputs.new_version }}
          files: GameEngine-v${{ steps.version.outputs.new_version }}.zip
          generate_release_notes: true
          body: |
            GameEngine Release v${{ steps.version.outputs.new_version }}

            ## Usage
             - Download the release package
             - Extract the package
             - Add the GameEngine-d.dll to your project
             - Link the GameEngine-d.lib to your project
             - Include the headers in your project

            ## Requirements
            - Windows
            - C++17 compatible compiler
            - SFML 2.6.x
            - Dear ImGui 1.91.x
            - ImGui-SFML 2.6.x
            - nlohmann_json 3.11.x

            ## Dependencies
            All dependencies are statically linked into the DLL, so you don't need to distribute them separately.
            However, you'll need them installed for development:

            ```cmake
            # CMake example
            find_package(SFML 2.6 COMPONENTS graphics window system REQUIRED)
            find_package(ImGui-SFML 2.6 REQUIRED)
            find_package(nlohmann_json 3.11 REQUIRED)
            ```

            ## Package Contents
            - bin/GameEngine-d.dll - Runtime library
            - lib/GameEngine-d.lib - Import library for linking
            - include/ - Header files
