name: Build GameEngine

on:
  workflow_call:
    inputs:
      build_command:
        description: "The build command to run"
        type: string
        required: true

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps_cache
            build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build and Test
        run: |
          chmod +x build.sh
          ${{ inputs.build_command }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/Testing/Temporary/LastTest.log
            build/test_results.xml
          retention-days: 30
