name: Build GameEngine

on:
  workflow_call:
    inputs:
      build_command:
        description: "The build command to run"
        type: string
        required: true
      upload_package:
        description: "Whether to upload the package artifact"
        type: boolean
        required: false
        default: false

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libudev-dev \
            libgl1-mesa-dev \
            xorg-dev

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps_cache
            build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build and Test
        run: |
          chmod +x build.sh
          ${{ inputs.build_command }}

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/Testing/Temporary/LastTest.log
            build/test_results.xml
          retention-days: 30

      - name: Upload GameEngine Package
        if: inputs.upload_package
        uses: actions/upload-artifact@v4
        with:
          name: GameEnginePackage
          path: package/
          retention-days: 30
