name: CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      build_command: ./build.sh -c -s -p
      upload_package: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" \) \
            -not -path "./build/*" \
            -not -path "./deps_cache/*" \
            -not -path "./package/*" \
            -not -path "./example_project/*" \
            -exec clang-format -style=file --dry-run --Werror {} +

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run static analysis
        run: |
          cppcheck \
            --enable=all \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --suppress=unusedFunction \
            --suppress=noExplicitConstructor \
            --suppress=unmatchedSuppression \
            --suppress=missingInclude \
            --inline-suppr \
            --std=c++17 \
            -I include \
            -I include/components \
            -I include/systems \
            src/ include/ include/components/ include/systems/
