name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            deps_cache
            build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build and Test
        run: |
          chmod +x build.sh
          ./build.sh -c -s -i "./install"

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: |
            build/Testing/Temporary/LastTest.log
            build/test_results.xml
          retention-days: 30

      - name: Upload GameEngine DLL
        uses: actions/upload-artifact@v3
        with:
          name: game-engine-lib
          path: |
            build/install/bin/GameEngine-d.lib
          retention-days: 30

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" \) \
            -not -path "./build/*" \
            -not -path "./deps_cache/*" \
            -exec clang-format -style=file --dry-run --Werror {} +

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run static analysis
        run: |
          cppcheck \
            --enable=all \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --suppress=unusedFunction \
            --suppress=noExplicitConstructor \
            --suppress=unmatchedSuppression \
            --suppress=missingInclude \
            --inline-suppr \
            --std=c++17 \
            -I include \
            -I components \
            -I systems \
            src/ include/ components/
