name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
            deps_cache
            build
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Configure CMake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          cd bin/${{env.BUILD_TYPE}}
          ./unit_tests.exe

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format --dry-run --Werror

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run static analysis
        run: |
          cppcheck --enable=all --error-exitcode=1 \
            --suppress=missingInclude \
            --suppress=unusedFunction \
            src/ include/ components/
