name: CI

on:
  push:
    branches: ["main", "master"]
    tags:
      - "v*.*.*"
  pull_request:
    branches: ["main", "master"]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get Version
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps_cache
            build/_deps
          key: ${{ runner.os }}-deps-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Build and Test
        run: |
          chmod +x build.sh
          ./build.sh -c -s -i "./install" -p

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            build/Testing/Temporary/LastTest.log
            build/test_results.xml
          retention-days: 30

      - name: Upload GameEngine Package
        uses: actions/upload-artifact@v4
        with:
          name: game-engine-v${{ env.VERSION }}
          path: package/
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          name: GameEngine v${{ env.VERSION }}
          files: |
            package/**/*
          body: |
            GameEngine Release v${{ env.VERSION }}

            ## What's Changed
            * See commit history for changes

            ## Installation
            1. Download the package
            2. Include the headers in your project
            3. Link against the library

            ## Requirements
            - Windows
            - C++17 compatible compiler
            - SFML 2.6.x
            - Dear ImGui 1.91.x
            - ImGui-SFML 2.6.x
            - nlohmann_json 3.11.x

            ## Dependencies
            All dependencies are statically linked into the DLL, so you don't need to distribute them separately.
            However, you'll need them installed for development:

            ```cmake
            # CMake example
            find_package(SFML 2.6 COMPONENTS graphics window system REQUIRED)
            find_package(ImGui-SFML 2.6 REQUIRED)
            find_package(nlohmann_json 3.11 REQUIRED)
            ```

            ## Included Files
            - bin/GameEngine-d.dll - Runtime library
            - lib/GameEngine-d.lib - Import library for linking
            - include/*.h - Header files
          draft: false
          prerelease: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: |
          find . -type f \( -name "*.cpp" -o -name "*.h" \) \
            -not -path "./build/*" \
            -not -path "./deps_cache/*" \
            -exec clang-format -style=file --dry-run --Werror {} +

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      - name: Run static analysis
        run: |
          cppcheck \
            --enable=all \
            --error-exitcode=1 \
            --suppress=missingIncludeSystem \
            --suppress=unusedFunction \
            --suppress=noExplicitConstructor \
            --suppress=unmatchedSuppression \
            --suppress=missingInclude \
            --inline-suppr \
            --std=c++17 \
            -I include \
            -I components \
            -I systems \
            src/ include/ components/
